server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

spring:
  redis:
    url: ${REDIS_URL:redis://localhost:6379}
    database: ${REDIS_DATABASE:0}

